# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run.
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build
        uses: docker://golang:1
        with:
          args: /bin/bash -c "go get github.com/mitchellh/gox && ./scripts/dist.sh"
        env:
          XDG_CACHE_HOME: /tmp/.cache
          HOME: /tmp/buildhome

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: build/sweetcher*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: compute next version
        uses: PssbleTrngle/VersionManagment@v1.0.8
        id: version
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          default-fragment: "bug"

      - name: update sonar config file
        run: sed -i -e "s/^sonar.projectVersion=.*$/sonar.projectVersion=${{ steps.version.outputs.next }}/" sonar-project.properties

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update sonar config
          committer: GitHub Actions <actions@github.com>
          author: GitHub Actions <actions@github.com>
          branch: post-release-sonar-config-update-${{ steps.version.outputs.next }}
          delete-branch: true
          base: master
          title: '[Release] Update Sonar config version to ${{ steps.version.outputs.next }}'
          body: |
            Update Sonar config version to ${{ steps.version.outputs.next }}
          labels: |
            release/automated_pr
          assignees: loicalbertin
          reviewers: loicalbertin
