name: Tests

on: [push, pull_request]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Unshallow to allow sonar to perform its analyze correctly
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Download deps
      run: |
        wget --output-document=gotestsum.tgz https://github.com/gotestyourself/gotestsum/releases/download/v1.11.0/gotestsum_1.11.0_linux_amd64.tar.gz
        tar xzf gotestsum.tgz gotestsum
        rm -f gotestsum.tgz

    - name: Test
      shell: bash
      run: |
        ./gotestsum --jsonfile tests-reports.json  -- -count=1 -coverprofile coverage-sonar.out -coverpkg=./... $(go list ./...)

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      if: ${{ ! github.event.pull_request.head.repo.fork }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}